apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-rhel9
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm-rhel9
        labels:
          dr: active
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9.6-image 
          namespace: openshift-virtualization-os-images 
        storage: {}
    - metadata:
        name: vm-rhel9-data
        labels:
          dr: active
      spec:
        preallocation: false
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 5Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
  instancetype:
    name: o1.medium 
  preference:
    name: rhel.9 
  runStrategy: RerunOnFailure
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - dataVolume:
            name: vm-rhel9
          name: rootdisk
        - dataVolume:
            name: vm-rhel9-data
          name: data
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: qt7y-iauh-kkl8
              user: rhel
          name: cloudinitdisk
